### ISSUE TITLE
NameError: name 'DEBUG_APPS' is not defined

### ISSUE THREAD

**Issue by ccf** [owocki/pytrader#11]
Hey Kevin, any idea what's causing this?

Including stack trace and my local_settings...

```[ccf@li286-238 pytrader]$ ./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ccf/tools/anaconda2/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/ccf/tools/anaconda2/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/home/ccf/tools/anaconda2/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/ccf/tools/anaconda2/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ccf/tools/anaconda2/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/ccf/tools/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ccf/projects/pytrader/pypolo/settings.py", line 124, in <module>
    INSTALLED_APPS += DEBUG_APPS
NameError: name 'DEBUG_APPS' is not defined
```

[ccf@li286-238 pytrader]$ cat pypolo/local_settings.py
```
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MAKE_TRADES=False

API_KEY="foo"
API_SECRET="bar"

#sqllite

_DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	}
}
```

**Comment by richardpetithory** [comment]
On [this line](https://github.com/owocki/pytrader/blob/master/pypolo/settings.py#L124) there is an inclusion from the `local_settings.py` file for a setting called `DEBUG_APPS`. Presumably this would be for things like Django Debug Toolbar or other such Django 'apps' that are specifically for development purposes.

Simply put `DEBUG_APPS = []` in your `local_settings.py` somewhere.

**Comment by owocki** [comment]
hey @ccf i've merged @richardpetithory 's fix into master.  pull & try now.

**Comment by owocki** [comment]
closing due to merged PR, feel free to re-open if you continue to have issues @ccf
