### ISSUE TITLE
kernel unicode issue

### ISSUE THREAD

**Issue by owocki** [owocki/pytrader#28]
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/root/pytrader/history/management/commands/predict_many_sk.py", line 42, in handle
    ct.get_classifier()
  File "/root/pytrader/history/models.py", line 329, in get_classifier
    clf.fit(self.X_train, self.y_train)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py", line 193, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py", line 251, in _dense_fit
    max_iter=self.max_iter, random_seed=random_seed)
TypeError: Argument 'kernel' has incorrect type (expected str, got unicode)
```

**Comment by owocki** [comment]
This is a python 2.7 issue, can be fixed by changing [this line](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/svm/base.py#L89) to 
```
self.kernel = str(kernel)
```
